### ISSUE TITLE
Unable to find template after creation/preview

### ISSUE THREAD

**Issue by chrisonline** [kimai/invoice-templates#5] opened 2023-01-05 09:20 UTC
I have tried the template `din5008-invoice.pdf.twig` and copied it to the "**invoices**" directory.  
It is now shown in the invoice templates and I can select it.  

Now if I try to show the invoice I get the following error:  
![image](https://user-images.githubusercontent.com/2077218/210744588-3b95f12f-8fa1-46d4-8562-92b890024226.png)  

Running it via **Docker compose** on a **Synology NAS**.  
Version 1.30.1 stable (prod)

Here is the template saved:  
![image](https://user-images.githubusercontent.com/2077218/210744782-228f044c-6d4b-4f7b-ac7e-d9b52a14fe30.png)  

I have not changed the template yet.

Can you help what I did wrong?

**Comment by kevinpapst** [comment] 2023-01-05 10:38
The part @SynoESStream sounds weird. That is not normal. 
Seems Synology (your setup) is somehow messing with the file loading streams of PHP.
Never seen before... that needs debugging in the system. 
I have no Synology available to test, maybe their community forum can help?

**Comment by chrisonline** [comment] 2023-01-05 10:49
So you think it is a problem because of the Synology? 
What exactly should I ask in the community forum? Can you send me the command what is used or any other related infos?
Because if I ask the same question in the Synology forum I think I get immediately back "ask the developer" ;-)
It is better if I can ask a more "general" question about php stream or something.

Alternative, I can of course test some commands inside the docker container via ssh if this would help.

**Comment by chrisonline** [comment] 2023-01-05 10:50
Have now tried to copy the invoice file and rename it to `din5008-invoice.pdf.twig@SynoEAStream` and now it is working.
Will ask now in the Synology forum what exactly this SynoEAStream is and let you know if I get more infos.

**Comment by kevinpapst** [comment] 2023-01-05 10:54
Wow, that is even weirder. 
Please check the var/invoices/ directory displaying all files (including hidden). 
Maybe this is some kind of Synology meta-data directory (thats what a quick search suggests).
Also check the invoice document dropdown, if there are multiple files you can select with the name `din5008-invoice`.

**Comment by chrisonline** [comment] 2023-01-05 13:43
There is indeed a hidden directory called `@eaDir`.
Seems this is something like the .thumb hidden folder on Windows to store some metadata of the files. 

If I delete this directory, it works.

So I think you parse the directory invoices and all subfolders.
And you find the file inside the `invoices` AND inside the `@eaDir`. 
Both are having the same name, so it shows in the invoice template selection only ones (I don't see it twice).

A good solution I think would be to ignore hidden folders if you search for the invoice templates.
Is this possible?

**Comment by kevinpapst** [comment] 2023-01-05 13:49
Aha, yeah right, Two files with the same name are not allowed. 
Kimai does not guarantee any order, so behavior is undefined. That is even documented in the invoices docs:
https://www.kimai.org/documentation/invoices.html#invoice-document

> Documents are addressed by their filename without extension (e.g. kimai.html.twig results in kimai)
> You can use every document name only once: so having kimai.html.twig and kimai.docx will lead to unpredictable results (the first file to be found takes precedence)

Regarding your question:

> A good solution I think would be to ignore hidden folders if you search for the invoice templates. Is this possible?

I am not entirely happy that I should fix the problems caused by another product^^ But yes, at some point I might add a filter. 

Even though you should probably just remove the directory and not use the Synology webfrontend (if that is the one creating those dirs & files).

**Comment by kevinpapst** [comment] 2023-01-05 14:56
Fixed. Closing.

**Closed as completed by kevinpapst** 2023-01-05 14:56 UTC

**Comment by chrisonline** [comment] 2023-01-05 15:13
Oh awesome, thanks for the really quick fix :-)

**Comment by pietervanuhm** [comment] 2025-07-25 14:38
i have the same issue in a Portainer docker environment, what can this be?

**Comment by chrisonline** [comment] 2025-07-26 12:55
@pietervanuhm Same error message as my screenshot in the first post?
Can you post more details?

**Comment by pietervanuhm** [comment] 2025-07-28 07:42
Ok i have downloaded the zip from the git repo via terminal in a folder, i moved for example 'din5008-invoice.pdf.twig' to the current folder:  '/opt/kimai/var/invoices', right after this the template is appearing in Kimai

<img width="367" height="296" alt="Image" src="https://github.com/user-attachments/assets/b1bf3da4-4131-499c-b4a7-24d842c64014" />

When i selected this template it shows this error message:

Lol at this moment of writing, i test it again and the template works... properly caching..?!

You can close this :) !
